# Generated by Django 4.1.13 on 2024-03-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='NombreMunicipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sexo',
        ),
        migrations.AddField(
            model_name='client',
            name='codigoReferencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='codigoReferencia'),
        ),
        migrations.AddField(
            model_name='client',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=10, unique=True, verbose_name='cedula'),
        ),
    ]
