# Generated by Django 4.1.13 on 2024-03-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_municipality_remove_client_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
        migrations.AddField(
            model_name='client',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='cedula'),
        ),
        migrations.AddField(
            model_name='client',
            name='municipality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.municipality'),
        ),
        migrations.AddField(
            model_name='client',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clasificacion'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigoReferencia',
            field=models.CharField(max_length=25, unique=True, verbose_name='codigoReferencia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='names',
            field=models.CharField(max_length=30, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surnames',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='celular'),
        ),
    ]
