# Generated by Django 4.1.13 on 2024-03-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_client_codigoreferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.CharField(choices=[('BUENO', 'B'), ('REGULAR', 'R'), ('MALO', 'M')], default='B', max_length=50, verbose_name='Clasificacion'),
        ),
    ]
