# Generated by Django 4.1.13 on 2024-03-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_client_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.CharField(choices=[('BUENO', 'BUENO'), ('REGULAR', 'REGULAR'), ('MALO', 'MALO')], default='B', max_length=50, verbose_name='Clasificacion'),
        ),
    ]
